export const REQUEST_FOR_ALLPRODUCTS = "REQUEST_FOR_ALLPRODUCTS";
export const SUCCESS_FOR_ALLPRODUCTS = "SUCCESS_FOR_ALLPRODUCTS";
export const FAIL_FOR_ALLPRODUCTS = "FAIL_FOR_ALLPRODUCTS";
export const REQUEST_FOR_CURRPROD = "REQUEST_FOR_CURRPROD";
export const SUCCESS_FOR_CURRPROD = "SUCCESS_FOR_CURRPROD";
export const FAIL_FOR_CURRPROD = "FAIL_FOR_CURRPROD";

export const ADD_IN_CART = "ADD_IN_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const DELETE_CART = "DELETE_CART";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const REQUEST_FOR_ORDER = "REQUEST_FOR_ORDER";
export const SUCCESS_FOR_ORDER = "SUCCESS_FOR_ORDER";
export const FAIL_FOR_ORDER = "FAIL_FOR_ORDER";
export const CLEAR_LATEST_ORDER_ID = "CLEAR_LATEST_ORDER_ID";
export const REQUEST_ALL_ORDERS = "REQUEST_ALL_ORDERS";
export const SUCCESS_ALL_ORDERS = "SUCCESS_ALL_ORDERS";
export const FAIL_ALL_ORDERS = "FAIL_ALL_ORDERS";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL";
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_REQUEST_SUCCESS = "SIGNUP_REQUEST_SUCCESS";
export const SIGNUP_REQUEST_FAIL = "SIGNUP_REQUEST_FAIL";
export const LOGOUT = "LOGOUT";
